name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  DeployToAzure:
    name: Deploy to Azure Static Web App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Verify zip file exists
        run: |
          test -f clss_deployment.zip

      - name: Unzip clss_deployment.zip
        run: |
          unzip -q clss_deployment.zip

      - name: Print files in directory after unzip
        run: ls -la clss_deployment

      - name: Update config.json with secrets
        run: |
          sed -i 's|"portalUrl": "${{ secrets.AGOL_PORTAL_URL }}"|g' clss_deployment/config.json
          sed -i "s|"username": "${{ secrets.AGOL_USERNAME }}"|g' clss_deployment/config.json
          sed -i 's|"password": "${{ secrets.AGOL_PASSWORD }}"|g' clss_deployment/config.json
          sed -i "s|"appUrl": "${{ secrets.AZURE_WEBSITE_URL }}"|g' clss_deployment/config.json
        working-directory: clss_deployment

      - name: Read config.json
        run: |
          cat clss_deployment/config.json

      - name: Run node script, deploy.js to create app code
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            node -e "require('./deploy.js').executeDeployment()"
          fi
        working-directory: clss_deployment

      - name: Deploy app to azure static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TEST_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/clss_deployment/app" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/clss_deployment/app" # Built app content directory - optional
          production_branch: "main"
          skip_app_build: true
          skip_api_build: true

    ###### End of Repository/Build Configurations  ######
