name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  DeployToAzure:
    name: Deploy to Azure Static Web App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Unzip clss_deployment.zip
        run: |
          unzip -q clss_deployment.zip

      - name: Update config.json with secret vrariables
        env:
          AGOL_PORTAL_URL: ${{ secrets.AGOL_PORTAL_URL }}
          AGOL_USERNAME: ${{ secrets.AGOL_USERNAME }}
          AGOL_PASSWORD: ${{ secrets.AGOL_PASSWORD }}
          AZURE_WEBSITE_URL: ${{ secrets.AZURE_WEBSITE_URL }}
        run: |
          sed -i "s|\"portalUrl\": \".*\"|\"portalUrl\": \"$AGOL_PORTAL_URL\"|g" clss_deployment/config.json
          sed -i "s|\"username\": \".*\"|\"username\": \"$AGOL_USERNAME\"|g" clss_deployment/config.json
          sed -i "s|\"password\": \".*\"|\"password\": \"$AGOL_PASSWORD\"|g" clss_deployment/config.json
          sed -i "s|\"appUrl\": \".*\"|\"appUrl\": \"$AZURE_WEBSITE_URL\"|g" clss_deployment/config.json

      - name: Check file info
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            node -e "require('./deploy.js').executeDeployment()"
          fi
        working-directory: clss_deployment

      - name: Deploy app to azure static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TEST_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/clss_deployment/app" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "app" # Built app content directory - optional
          production_branch: "main"
          skip_app_build: true
          skip_api_build: true

    ###### End of Repository/Build Configurations  ######
