name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  DeployToAzure:
    name: Deploy to Azure Static Web App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Unzip deployment package
        run: unzip -q clss_deployment_package.zip -d clss_deployment_package
      - name: Move to deployment package directory
        run: cd clss_deployment_package
      - name: Update config.json with secrets
        run: |
          sed -i "s|\"portalUrl\": \"${{ secrets.AGOL_PORTAL_URL }}\"|g" clss_deployment_package/config.json
          sed -i "s|\"username\": \"${{ secrets.AGOL_USERNAME }}\"|g" clss_deployment_package/config.json
          sed -i "s|\"password\": \"${{ secrets.AGOL_PASSWORD }}\"|g" clss_deployment_package/config.json
          sed -i "s|\"appUrl\": \"${{ secrets.AZURE_WEBSITE_URL }}\"|g" clss_deployment_package/config.json

      - name: Run node script, deploy.js to create app code
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            node -e "require('./deploy.js').executeDeployment()" 
          fi

      - name: Deploy app to azure static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TEST_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/clss_deployment_package/app" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/clss_deployment_package/app" # Built app content directory - optional
          production_branch: "main"
          skip_app_build: true
          skip_api_build: true

          ###### End of Repository/Build Configurations  ######
